// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ-B5A5HUyYiyh-y3quG-6AEGL7xABtr0',
    appId: '1:1019331281361:android:bc6b70549ed3453229e0f0',
    messagingSenderId: '1019331281361',
    projectId: 'bumpo-3b1c3',
    storageBucket: 'bumpo-3b1c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJd9wMLXZTYXMwHVzqCH6tngcslIzb2Zs',
    appId: '1:1019331281361:ios:e5de039d074e346d29e0f0',
    messagingSenderId: '1019331281361',
    projectId: 'bumpo-3b1c3',
    storageBucket: 'bumpo-3b1c3.appspot.com',
    iosBundleId: 'com.bumpo.haleem.bumpo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXguVNJqMlpKPmUEiq3mQoWNyPG3gVYYg',
    appId: '1:1019331281361:web:0f0a6a4933053a9f29e0f0',
    messagingSenderId: '1019331281361',
    projectId: 'bumpo-3b1c3',
    authDomain: 'bumpo-3b1c3.firebaseapp.com',
    storageBucket: 'bumpo-3b1c3.appspot.com',
  );

}